version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: madior
      MYSQL_DATABASE: school
      MYSQL_USER: madior
      MYSQL_PASSWORD: madior
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: springboot-dev
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    command: ./mvnw spring-boot:run

volumes:
  db_data:
