version: '3.8'

services:
  springboot:
    build: .
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cuatro
      SPRING_DATASOURCE_USERNAME: madior
      SPRING_DATASOURCE_PASSWORD: madior
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: cuatro
      MYSQL_USER: madior
      MYSQL_PASSWORD: madior
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

